# fly.toml app configuration file generated for ask-ai-server on 2023-10-02T19:08:42+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ask-ai-server"
primary_region = "mia"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
