# fly.toml app configuration file generated for ask-ai-client on 2023-10-02T19:09:06+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ask-ai-client"
primary_region = "mia"

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
